#!/bin/bash

sleep 1
exec 2>&1
if [ -f /var/run/a2b-callback-daemon.pid ]; then
    kill `cat /var/run/a2b-callback-daemon.pid`
fi
date "+%F starting asterisk at %X"
exec setuidgid asterisk /usr/sbin/asterisk -ftTnp
